feat(postgresql/docker): Added docker compose to initialize an instance of Postgres
stevensblueprint/nycmesh-node-visualizer pull request #40
Opened 2023-10-24 22:01 UTC by miguel-merlin

#32

2023-10-24 22:54 UTC, JonMike8 approved these changes

2023-10-25 07:03 UTC, ericzty requested changes

2023-10-25 07:03 UTC, ericzty commented on docker-compose.yaml
why are we exposing the postgres port here? If we put the backend in the same network then we don't have to expose it.

POSTGRES_USER, POSTGRES_PASSWORD should be env vars and not preset in the docker-compose.
RE: POSTGRES_DB, let's just name it nycmesh

2023-10-26 12:31 UTC, miguel-merlin commented on docker-compose.yaml
Just pushed the changes!

2023-10-27 20:13 UTC, ericzty commented
Relates to #15

2023-10-27 20:23 UTC, ericzty commented
Could you push a .env.example with example env files.
the rest looks good

2023-10-31 12:23 UTC, miguel-merlin commented
> Could you push a .env.example with example env files. the rest looks good

Done!

2023-10-31 14:19 UTC, ericzty approved these changes

2023-10-31 14:19 UTC, merged