feat(ci/cd): Changed lintstaged to prettier-check, also added format and format:fix script, and also added check.yml for prettier & eslint github action
stevensblueprint/nycmesh-node-visualizer pull request #47
Opened 2023-11-01 23:39 UTC by OwenTruong

I have changed lintstaged to prettier-check so it checks instead of fix/format when someone runs git commit. Also added format and format:fix script in package.json. And also added a [check.yml](/.github/workflows/check.yml) for running prettier and eslint check when someone makes a PR request.

2023-11-02 00:06 UTC, ericzty commented
#15

2023-11-02 00:09 UTC, ericzty requested changes
Nice work, please see comments.

2023-11-02 00:09 UTC, ericzty commented on .github/workflows/check.yml
Could you split the prettier and lint into two separate test jobs?
let’s also disable fail-fast in the strat, and make them run concurrently. 
Could you also rename it from test to something more descriptive?

2023-11-02 00:48 UTC, ericzty requested changes

2023-11-02 00:48 UTC, ericzty commented on .github/workflows/check.yml
we only want the test on ubuntu-latest.

2023-11-02 00:48 UTC, ericzty commented on .github/workflows/check.yml
rest looks good

2023-11-02 00:52 UTC, OwenTruong commented on .github/workflows/check.yml
Thanks for the feedback! I am new to this so I appreciate the comments

2023-11-02 00:53 UTC, OwenTruong commented
Squashed all 4 commits into one

2023-11-05 16:27 UTC, miguel-merlin approved these changes

2023-11-05 16:27 UTC, merged